CREATE DATABASE IF NOT EXISTS gamesdb;

USE	gamesdb;

DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;

CREATE TABLE IF NOT EXISTS customers(
	id INT PRIMARY KEY AUTO_INCREMENT,
    fname VARCHAR(60) NOT NULL,
    lname VARCHAR(60) NOT NULL,
    age INT,
    contact CHAR(11)
);
    
CREATE TABLE IF NOT EXISTS products(
	id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    genre VARCHAR(30),
    price FLOAT
);

CREATE TABLE IF NOT EXISTS orders(
	id INT PRIMARY KEY AUTO_INCREMENT,
    dateofpurchase DATETIME NOT NULL,
    custid INT NOT NULL,
    prodid INT NOT NULL,
    FOREIGN KEY(custid) REFERENCES customers(id),
    FOREIGN KEY(prodid) REFERENCES products(id)
);